"""Crash report class module.

This module defines data structures in which to store crash information.
"""


class CrashReport(object):
    """A structure in which to store information about a single crash.

    Attributes:
        input_file:  A string representing the input file name that caused this
                     particular crash.
        commands:     The command, as a list, that was run to cause the crash.
        signal:      A string representing the signal that was generated by the
                     crash e.g SIGSEGV
        stack_trace: The stack trace after the crash as a list of StackFrame
                     objects.
        error_msg:   The error message string that was output when the crash
                     occurred.
    """
    def __init__(self, input_file, commands, signal, stack_trace, error_msg):
        self.input_file = input_file
        self.commands = commands
        self.signal = signal
        self.stack_trace = stack_trace
        self.error_msg = error_msg

    def make_frame_str(self, index, frame):
        return "#{!s} {!s}".format(index, frame)

    def make_trace_str(self):
        if not self.stack_trace:
            return None
        out = []
        for index, frame in enumerate(self.stack_trace):
            out.append(self.make_frame_str(index, frame))
        return "\n".join(out)

    def __str__(self):
        return ("Input file: {0.input_file!s}\n"
                "Command: {1!s}\n"
                "Signal: {0.signal!s}\n"
                "Stack trace:\n{2!s}\n"
                "Error message:\n"
                "{0.error_msg!s}").format(self, " ".join(self.commands),
                                          self.make_trace_str())


class StackFrame(object):
    """A structure in which to store information about a stack frame.

    Attributes:
        function: The function name that this stack frame refers to.
        filename: The filename that this stack frame refers to.
        line_num: The line number that this stack frame refers to.
    """
    def __init__(self, function, filename, line_num):
        self.function = function
        self.filename = filename
        self.line_num = line_num

    def __str__(self):
        return "{!s}:{!s}: {!s}()".format(self.filename,
                                          self.line_num, self.function)

    def __eq__(self, other):
        return (self.function == other.function and
                self.filename == other.filename and
                self.line_num == other.line_num)
